trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  workingDir: ./holiday-entitlement-test

steps:
  - task: UseNode@1
    inputs:
      version: '18.x'
    displayName: 'Install Node.js 18'

  - script: npm ci
    workingDirectory: $(workingDir)
    displayName: 'Install dependencies'

  - script: npx playwright install --with-deps chromium
    workingDirectory: $(workingDir)
    displayName: 'Install Playwright Chromium browser'

  - script: npx playwright test --grep regression 
    workingDirectory: $(workingDir)
    displayName: 'Run Playwright tests'
    env:
      CI: 'true'

  - task: PublishTestResults@2
    displayName: 'Publish test results'
    inputs:
      searchFolder: '$(workingDir)/test-results'
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*.xml'
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: 'Playwright UI Tests'
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Playwright HJTML report'
    inputs:
      targetPath: '$(workingDir)/playwright-report'
      artifact: playwright-report
      publishLocation: pipeline
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Playwright traces'
    condition: and(succeededOrFailed(), exists('$(workingDir)/playwright-traces'))
    inputs:
      targetPath: '$(workingDir)/playwright-traces'
      artifact: traces
